### ISSUE TITLE
Remove Why are you selling tickets before speakers are announced?

### ISSUE THREAD

**Issue by kristjanmik** [jsis/jsconf.is#57]
On the ticket page we have a paragraph regarding selling tickets before speakers are announced, it can be removed since we announced all the speakers.
<img width="935" alt="screen shot 2016-04-16 at 15 56 37" src="https://cloud.githubusercontent.com/assets/911107/14582119/d0b69cc8-03eb-11e6-87b3-865987fffd60.png">

**Comment by benediktvaldez** [comment]
I suggest we simply change it to - since I feel the rest is still relevant.. What do you think @kristjanmik?

### Why are you selling all the tickets so early?
Iceland is an especially popular tourist destination in the summer. We want to give attendees the chance to make their travel arrangements as far in advance as possible to get the most choices and the best prices.
